# Generated by Django 5.0.6 on 2024-07-19 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
