# Generated by Django 5.0.6 on 2024-09-03 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='is_thumbnail',
            field=models.BooleanField(default=False),
        ),
    ]
