# Generated by Django 5.0.6 on 2024-09-04 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_experience_job_rename_education_school_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='job',
            table=None,
        ),
        migrations.AlterModelTable(
            name='school',
            table=None,
        ),
    ]
