# Generated by Django 5.0.6 on 2024-09-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_job_table_alter_school_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='state',
            field=models.CharField(default='MN', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='state',
            field=models.CharField(default='MN', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.CharField(max_length=30),
        ),
    ]
