# Generated by Django 5.0.6 on 2024-09-04 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_job_state_school_state_alter_job_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='school',
            new_name='name',
        ),
    ]
