# Generated by Django 5.0.6 on 2024-09-04 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_school_school_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_title',
            new_name='title',
        ),
    ]
