# Generated by Django 5.0.6 on 2024-09-11 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_contact_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
