# Generated by Django 5.0.6 on 2024-09-13 03:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_project_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.IntegerField(default=0, help_text='The higher the number, the higher the priority'),
        ),
    ]
