# Generated by Django 5.0.6 on 2024-09-13 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_contact_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='timestamp',
            new_name='date_sent',
        ),
    ]
