# Generated by Django 5.0.6 on 2024-09-13 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_timestamp_contact_date_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='date_sent',
            new_name='time_sent',
        ),
    ]
